name: Update plugin assets/readme in the WP repo
on:
  push:
    branches:
      - main
    paths:
      - readme.txt
      - assets/**
jobs:
  assets:
    name: Update WordPress.org assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install subversion -y

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        with:
          dry-run: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: block-editor-image-filename-prompt
